name: TopPvP
main: com.CastawayDevelopment.TopPvP.TopPvP
version: 0.1

author: Castaway Development Group

description: This is a leaderboard plugin that utilizes the scoreboard to display players kills, dealths, and much more! 
website: www.castawaydev.org