name: TopPvP
version: 0.0.1
website: http://castawaydev.org
main: org.CastawayDevelopment.TopPvP.TopPvP

commands:
  toppvp:
    description: default command for TopPvP
    usage: /<command> help for help
    aliases: [bounty]